# Generated by Django 2.1.4 on 2019-01-15 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181217_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='message',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
